global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: eventservice
    static_configs:
      - targets: ["events:9100"]
  - job_name: bookingservice
    static_configs:
      - targets: ["bookings:9100"]